name: CI

on:
  push:
    branches: ['*']
    tags: ['*']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-lint')"
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Linter Check
        run: deno lint

  fmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-fmt')"
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Formatter Check
        run: deno fmt --check

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-test')"
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Run Tests
        run: deno test

  release:
    runs-on: ubuntu-latest
    needs: [ lint, fmt, test ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true